# Generated by Django 6.0 on 2025-12-10 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundamentoLegal',
            fields=[
                ('seq', models.IntegerField(primary_key=True, serialize=False, verbose_name='Sequencial')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('glossario', models.TextField(blank=True, null=True, verbose_name='Glossário')),
                ('tipo_recurso', models.CharField(choices=[('AFIRE', 'Fundamentos de Inadmissão REsp'), ('AFIPO_RESP', 'REsp e AREsp'), ('AFIPO_RMS', 'RMS - Recurso em Mandado de Segurança'), ('AFIREQ', 'Requisitos de Fundamentos')], max_length=20, verbose_name='Tipo de Recurso')),
                ('categoria', models.CharField(choices=[('CIVEL', 'Cível'), ('CRIMINAL', 'Criminal'), ('GERAL', 'Geral')], default='GERAL', max_length=20, verbose_name='Categoria')),
                ('neutro', models.BooleanField(default=False, verbose_name='Neutro')),
                ('informacao', models.BooleanField(default=False, verbose_name='Informação')),
                ('justificativa', models.BooleanField(default=False, verbose_name='Justificativa')),
                ('selecionavel', models.BooleanField(default=True, verbose_name='Selecionável')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filhos', to='fundamentos.fundamentolegal', verbose_name='Fundamento Pai')),
            ],
            options={
                'verbose_name': 'Fundamento Legal',
                'verbose_name_plural': 'Fundamentos Legais',
                'ordering': ['tipo_recurso', 'seq'],
            },
        ),
        migrations.CreateModel(
            name='TextoFundamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legislacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Legislação')),
                ('texto_html', models.TextField(verbose_name='Texto em HTML')),
                ('fundamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textos', to='fundamentos.fundamentolegal', verbose_name='Fundamento')),
            ],
            options={
                'verbose_name': 'Texto de Fundamento',
                'verbose_name_plural': 'Textos de Fundamentos',
            },
        ),
        migrations.AddIndex(
            model_name='fundamentolegal',
            index=models.Index(fields=['tipo_recurso'], name='fundamentos_tipo_re_333780_idx'),
        ),
        migrations.AddIndex(
            model_name='fundamentolegal',
            index=models.Index(fields=['categoria'], name='fundamentos_categor_9722cd_idx'),
        ),
        migrations.AddIndex(
            model_name='fundamentolegal',
            index=models.Index(fields=['descricao'], name='fundamentos_descric_1b1308_idx'),
        ),
    ]
